services:
  agora-database:
    image: mariadb:latest
    container_name: agora-database
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agora_db
      MYSQL_USER: agora_user
      MYSQL_PASSWORD: agora_pass
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  agora-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: agora-api-dev
    restart: on-failure
    depends_on:
      agora-database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    profiles:
      - dev
    command: ["yarn", "dev"]

  agora-api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: agora-api-prod
    restart: on-failure
    depends_on:
      agora-database:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    profiles:
      - prod
    command: ["node", "dist/src/server.js"]

volumes:
  database-data: